### ISSUE TITLE
Loading assets not referenced by a map

### ISSUE THREAD

**Issue by WastellR** [paterron/UE5MMExample#2]
Hi,
I've found this repository an extremely helpful reference for a game I'm building with mod support, thanks very much for making it. I have an issue not with your code but with Unreal in general that you might be able to help me with.

When loading an asset in a .pak file, it seems to be impossible to load any asset that doesn't have an instance of itself in a map somewhere, even if you make that asset into a primary asset or make a primary asset that isn't a map to reference it. You seem to have come up against the same issue, and in your 'mod' projects in this repo get around it by just having an empty level that contains an instance of the asset you want to load + spawn from the .pak.

Am I right in thinking that this is just a hard limit of the engine and there's no elegant way around it? I just have to make sure to make an empty level that holds instances of all assets I want to package when I make a .pak.

Thanks very much for any help :)

**Comment by paterron** [comment]
You are right. I tried to create a level from scratch but never succeeded.
However, a default empty level seems always to work with 5.3.

**Comment by WastellR** [comment]
Ah thanks for the confirmation. I will let you know if I ever find a better way around the problem.
